#DB-SOURCE
spring:
  datasource:
    mysql:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.103:3306/logo_online?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&noAccessToProcedureBodies=true&allowMultiQueries=true&autoReconnect=true
      username: root
      password: 123456
      hikari:
        minimum-idle: 5
        #<!-- 缺省值：10；计算公式：((core_count * 2) + effective_spindle_count) ，解释core_count：cpu 内核数， effective_spindle_count 硬盘挂载数量 -->
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        pool-name: MysqlHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000

#LOGBACK CONFIG
logging:
  config: classpath:logback-spring.xml
  logback:
    rollingpolicy:
      max-file-size: 250MB
      max-history: 1
      total-size-cap: 1GB
      clean-history-on-start: true
  root:
    level: debug
    path: ./logs