const a = {
  "code": "0",
  "msg": "操作成功",
  "data": {
      "id": 51,
      "name": "标题",
      "domItem": "{\"title\":\"标题\",\"pages\":[{\"uuid\":1691287137342,\"title\":\"\",\"elements\":[{\"name\":\"lbp-picture\",\"pluginType\":\"lbp-picture\",\"uuid\":\"lbp-picture_16ef6e4a-6769-9b0f-4be5-0c61e5bd2989\",\"pluginProps\":{\"uuid\":\"lbp-picture_16ef6e4a-6769-9b0f-4be5-0c61e5bd2989\",\"imgSrc\":\"https://www.baidu.com/img/flexible/logo/pc/result@2.png\",\"fillType\":\"vertical-center\"},\"commonStyle\":{\"top\":38,\"left\":8,\"width\":307,\"height\":120,\"zindex\":1,\"textAlign\":\"center\",\"color\":\"#000000\",\"backgroundColor\":\"rgba(255, 255, 255, 0)\",\"fontSize\":14,\"margin\":{\"top\":{\"value\":0,\"unit\":\"px\"},\"right\":{\"value\":0,\"unit\":\"px\"},\"bottom\":{\"value\":0,\"unit\":\"px\"},\"left\":{\"value\":0,\"unit\":\"px\"}},\"padding\":{\"top\":{\"value\":0,\"unit\":\"px\"},\"right\":{\"value\":0,\"unit\":\"px\"},\"bottom\":{\"value\":0,\"unit\":\"px\"},\"left\":{\"value\":0,\"unit\":\"px\"}},\"border\":{\"top\":{\"value\":0,\"unit\":\"px\"},\"right\":{\"value\":0,\"unit\":\"px\"},\"bottom\":{\"value\":0,\"unit\":\"px\"},\"left\":{\"value\":0,\"unit\":\"px\"},\"color\":{\"value\":\"#000\"},\"style\":{\"value\":\"solid\"}},\"border-style\":\"solid\",\"boxModelPart\":\"\",\"angle\":0},\"events\":[],\"methodList\":[],\"scripts\":[],\"animations\":[]},{\"name\":\"lbp-text-tinymce\",\"pluginType\":\"lbp-text-tinymce\",\"uuid\":\"lbp-text-tinymce_d2d7b1c3-d22c-c0cb-e892-fcf92d8d2d90\",\"pluginProps\":{\"uuid\":\"lbp-text-tinymce_d2d7b1c3-d22c-c0cb-e892-fcf92d8d2d90\",\"fontColor\":\"#000\",\"fontFamily\":\"\",\"fontSize\":14,\"letterSpacing\":0,\"writingMode\":\"horizontal-tb\",\"borderWidth\":0,\"borderRadius\":10,\"borderColor\":\"#000000\",\"text\":\"双击修改文字\",\"editorMode\":\"preview\",\"isEditingElement\":false},\"commonStyle\":{\"top\":58,\"left\":19,\"width\":100,\"height\":40,\"zindex\":2,\"textAlign\":\"center\",\"color\":\"#000000\",\"backgroundColor\":\"rgba(255, 255, 255, 0)\",\"fontSize\":14,\"margin\":{\"top\":{\"value\":0,\"unit\":\"px\"},\"right\":{\"value\":0,\"unit\":\"px\"},\"bottom\":{\"value\":0,\"unit\":\"px\"},\"left\":{\"value\":0,\"unit\":\"px\"}},\"padding\":{\"top\":{\"value\":0,\"unit\":\"px\"},\"right\":{\"value\":0,\"unit\":\"px\"},\"bottom\":{\"value\":0,\"unit\":\"px\"},\"left\":{\"value\":0,\"unit\":\"px\"}},\"border\":{\"top\":{\"value\":0,\"unit\":\"px\"},\"right\":{\"value\":0,\"unit\":\"px\"},\"bottom\":{\"value\":0,\"unit\":\"px\"},\"left\":{\"value\":0,\"unit\":\"px\"},\"color\":{\"value\":\"#000\"},\"style\":{\"value\":\"solid\"}},\"border-style\":\"solid\",\"boxModelPart\":\"\",\"angle\":0},\"events\":[],\"methodList\":[],\"scripts\":[],\"animations\":[]}]}],\"backgroundColor\":\"rgba(0, 0, 0, 0)\",\"style\":\"1\",\"datasources\":[],\"cover_image_url\":\"/savePath/material/2023/08/06/B35A534385FD4EB18AF52183C85B615D.png\",\"is_publish\":false,\"is_template\":false,\"width\":320,\"height\":164,\"page_mode\":\"h5_swipper\"}",
      "releaseStatus": "2",
      "style": "1"
  }
}
export default a